repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.5
    hooks:
      # Formatter: Ensures consistent code style
      - id: ruff-format
        args: [ "-v" ]
        files: ^backend/

  - repo: local
    hooks:
      - id: ty
        name: ty check
        # Move into the backend folder and run ty from the local venv
        entry: bash -c "cd backend && .venv/bin/ty check ."
        language: system
        types: [python]
        pass_filenames: false # Ty checks the whole project context at once